name: kartal
description: Kartal is an extension package for easy to use at app development
  time. You can access more features with primitive variables(context, string
  etc.).
version: 2.1.1
homepage: https://github.com/VB10/kartal

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  mime: ^1.0.0
  package_info_plus: ^1.0.4
  pedantic: ^1.10.0
  share: ^2.0.0
  url_launcher: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
