name: kartal
description: Kartal is an extension package for easy to use at app development
  time. You can access more features with primitive variables(context, string
  etc.).
version: 2.3.0
homepage: https://github.com/VB10/kartal

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info: ^2.0.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.0
  package_info_plus: ^1.0.6

  share: ^2.0.0
  url_launcher: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
